import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Client = { id:string; full_name:string; document_id:string|null; phone:string|null; email:string|null; address:string|null; status:'activo'|'inactivo' }
type ClientForm = { full_name:string; document_id:string; phone:string; email:string; address:string; status:'activo'|'inactivo' }
const empty: ClientForm = { full_name:'', document_id:'', phone:'', email:'', address:'', status:'activo' }

export default function Clients() {
  const [clients,setClients]=useState<Client[]>([]); const [form,setForm]=useState(empty); const [search,setSearch]=useState(''); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Client|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
  const load=async()=>{if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('clients').select('*').order('created_at',{ascending:false});setLoading(false);if(error)setMessage(`No se pudieron cargar los clientes: ${error.message}`);else setClients(data as Client[])}
  useEffect(()=>{load()},[])
  const close=()=>{setShowForm(false);setEditing(null);setForm(empty)}
  const startEdit=(client:Client)=>{setEditing(client);setForm({full_name:client.full_name,document_id:client.document_id??'',phone:client.phone??'',email:client.email??'',address:client.address??'',status:client.status});setShowForm(true)}
  const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const isEditing=Boolean(editing);setSaving(true);setMessage('');const request=editing?supabase.from('clients').update(form).eq('id',editing.id):supabase.from('clients').insert(form);const {error}=await request;setSaving(false);if(error){setMessage(`No se pudo guardar: ${error.message}`);return}close();setMessage(isEditing?'Cliente actualizado correctamente.':'Cliente registrado correctamente.');load()}
  const remove=async(client:Client)=>{if(!supabase||!confirm(`¿Eliminar a ${client.full_name}?`))return;const {error}=await supabase.from('clients').delete().eq('id',client.id);if(error)setMessage(`No se pudo eliminar: ${error.message}`);else{setMessage('Cliente eliminado.');load()}}
  const shown=clients.filter(c=>`${c.full_name} ${c.phone??''} ${c.document_id??''}`.toLowerCase().includes(search.toLowerCase()))
  return <><header><div><span className="eyebrow">GESTIÓN</span><h1>Clientes</h1><p>Directorio de solicitantes y clientes activos.</p></div><button onClick={()=>{setEditing(null);setForm(empty);setShowForm(true)}}>+ Nuevo cliente</button></header>{message&&<p className="message">{message}</p>}{showForm&&<section className="panel form-panel"><div className="form-title"><h2>{editing?'Editar cliente':'Registrar cliente'}</h2><button className="secondary" onClick={close}>Cancelar</button></div><form className="client-form" onSubmit={save}><label>Nombre completo*<input value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required /></label><label>Documento<input value={form.document_id} onChange={e=>setForm({...form,document_id:e.target.value})}/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Correo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="wide">Dirección<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Estado<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as 'activo'|'inactivo'})}><option value="activo">Activo</option><option value="inactivo">Inactivo</option></select></label><div className="wide"><button disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Guardar cliente'}</button></div></form></section>}<section className="panel table"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar clientes…"/><span>{shown.length} cliente(s)</span></div><table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Documento</th><th>Estado</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Cargando clientes…</td></tr>:shown.length===0?<tr><td colSpan={5}>No hay clientes registrados aún.</td></tr>:shown.map(c=><tr key={c.id}><td>{c.full_name}<small className="subtext">{c.email}</small></td><td>{c.phone||'—'}</td><td>{c.document_id||'—'}</td><td><span className={`badge ${c.status}`}>{c.status}</span></td><td><div className="row-actions"><button className="secondary" onClick={()=>startEdit(c)}>Editar</button><button className="danger" onClick={()=>remove(c)}>Eliminar</button></div></td></tr>)}</tbody></table></section></>
}
