import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Client={id:string;full_name:string}; type Vehicle={id:string;make:string;model:string;year:number|null;status:string}; type Financing={id:string;principal:number;annual_rate:number;term_months:number;start_date:string;status:string;clients:Client;vehicles:Vehicle|null}
const empty={client_id:'',vehicle_id:'',principal:'',annual_rate:'0',term_months:'',start_date:new Date().toISOString().slice(0,10)}
const money=new Intl.NumberFormat('es-US',{style:'currency',currency:'USD'})

export default function Financings(){
 const [items,setItems]=useState<Financing[]>([]);const [clients,setClients]=useState<Client[]>([]);const [vehicles,setVehicles]=useState<Vehicle[]>([]);const [form,setForm]=useState(empty);const [show,setShow]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('')
 const load=async()=>{if(!supabase)return;setLoading(true);const [f,c,v]=await Promise.all([supabase.from('financings').select('*,clients(id,full_name),vehicles(id,make,model,year,status)').order('created_at',{ascending:false}),supabase.from('clients').select('id,full_name').eq('status','activo').order('full_name'),supabase.from('vehicles').select('id,make,model,year,status').eq('status','disponible').order('make')]);setLoading(false);if(f.error)setMessage(`No se pudieron cargar los financiamientos: ${f.error.message}`);else setItems(f.data as Financing[]);setClients(c.data??[]);setVehicles(v.data??[])}
 useEffect(()=>{load()},[])
 const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setMessage('');const {error}=await supabase.from('financings').insert({...form,vehicle_id:form.vehicle_id||null,principal:Number(form.principal),annual_rate:Number(form.annual_rate),term_months:Number(form.term_months)});if(!error&&form.vehicle_id)await supabase.from('vehicles').update({status:'financiado'}).eq('id',form.vehicle_id);setSaving(false);if(error){setMessage(`No se pudo guardar: ${error.message}`);return}setForm(empty);setShow(false);setMessage('Financiamiento registrado correctamente.');load()}
 return <><header><div><span className="eyebrow">GESTIÓN</span><h1>Financiamientos</h1><p>Contratos, plazos, tasas y saldos.</p></div><button onClick={()=>setShow(true)}>+ Nuevo financiamiento</button></header>{message&&<p className="message">{message}</p>}{show&&<section className="panel form-panel"><div className="form-title"><h2>Nuevo financiamiento</h2><button className="secondary" onClick={()=>setShow(false)}>Cancelar</button></div><form className="client-form" onSubmit={save}><label>Cliente*<select value={form.client_id} onChange={e=>setForm({...form,client_id:e.target.value})} required><option value="">Selecciona un cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><label>Vehículo<select value={form.vehicle_id} onChange={e=>setForm({...form,vehicle_id:e.target.value})}><option value="">Sin vehículo asignado</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.make} {v.model} {v.year??''}</option>)}</select></label><label>Monto financiado*<input type="number" min="0.01" step="0.01" value={form.principal} onChange={e=>setForm({...form,principal:e.target.value})} required/></label><label>Tasa anual (%)<input type="number" min="0" step="0.01" value={form.annual_rate} onChange={e=>setForm({...form,annual_rate:e.target.value})} required/></label><label>Plazo (meses)*<input type="number" min="1" value={form.term_months} onChange={e=>setForm({...form,term_months:e.target.value})} required/></label><label>Fecha de inicio*<input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} required/></label><div className="wide"><button disabled={saving}>{saving?'Guardando…':'Guardar financiamiento'}</button></div></form></section>}<section className="panel table"><div className="toolbar"><span>{items.length} financiamiento(s)</span><span>Solo se muestran vehículos disponibles al crear uno nuevo.</span></div><table><thead><tr><th>Cliente</th><th>Vehículo</th><th>Monto</th><th>Plazo</th><th>Estado</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Cargando financiamientos…</td></tr>:items.length===0?<tr><td colSpan={5}>No hay financiamientos registrados aún.</td></tr>:items.map(i=><tr key={i.id}><td>{i.clients?.full_name}</td><td>{i.vehicles?`${i.vehicles.make} ${i.vehicles.model}`:'—'}</td><td>{money.format(i.principal)}</td><td>{i.term_months} meses<small className="subtext">{i.annual_rate}% anual</small></td><td><span className="badge activo">{i.status}</span></td></tr>)}</tbody></table></section></>
}
