import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Financing={id:string;principal:number;clients:{full_name:string};vehicles:{make:string;model:string}|null};type Payment={id:string;amount:number;paid_at:string;method:string;reference:string|null;financings:Financing}
const empty={financing_id:'',amount:'',paid_at:new Date().toISOString().slice(0,10),method:'efectivo',reference:'',notes:''};const money=new Intl.NumberFormat('es-US',{style:'currency',currency:'USD'})

export default function Payments(){
 const [payments,setPayments]=useState<Payment[]>([]);const [financings,setFinancings]=useState<Financing[]>([]);const [form,setForm]=useState(empty);const [show,setShow]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('')
 const load=async()=>{if(!supabase)return;setLoading(true);const [p,f]=await Promise.all([supabase.from('payments').select('*,financings(id,principal,clients(full_name),vehicles(make,model))').order('paid_at',{ascending:false}),supabase.from('financings').select('id,principal,clients(full_name),vehicles(make,model)').eq('status','activo').order('created_at',{ascending:false})]);setLoading(false);if(p.error)setMessage(`No se pudieron cargar los pagos: ${p.error.message}`);else setPayments((p.data??[]) as unknown as Payment[]);setFinancings((f.data??[]) as unknown as Financing[])}
 useEffect(()=>{load()},[])
 const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setSaving(true);setMessage('');const {error}=await supabase.from('payments').insert({...form,amount:Number(form.amount)});setSaving(false);if(error){setMessage(`No se pudo guardar: ${error.message}`);return}setForm(empty);setShow(false);setMessage('Pago registrado correctamente.');load()}
 return <><header><div><span className="eyebrow">GESTIÓN</span><h1>Pagos</h1><p>Cobranza, pagos aplicados y vencimientos.</p></div><button onClick={()=>setShow(true)}>+ Registrar pago</button></header>{message&&<p className="message">{message}</p>}{show&&<section className="panel form-panel"><div className="form-title"><h2>Registrar pago</h2><button className="secondary" onClick={()=>setShow(false)}>Cancelar</button></div><form className="client-form" onSubmit={save}><label className="wide">Financiamiento*<select value={form.financing_id} onChange={e=>setForm({...form,financing_id:e.target.value})} required><option value="">Selecciona un financiamiento</option>{financings.map(f=><option key={f.id} value={f.id}>{f.clients?.full_name} — {f.vehicles?`${f.vehicles.make} ${f.vehicles.model}`:'Sin vehículo'} — {money.format(f.principal)}</option>)}</select></label><label>Monto*<input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label>Fecha*<input type="date" value={form.paid_at} onChange={e=>setForm({...form,paid_at:e.target.value})} required/></label><label>Método<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="cheque">Cheque</option></select></label><label>Referencia<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="wide">Notas<input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="wide"><button disabled={saving}>{saving?'Guardando…':'Guardar pago'}</button></div></form></section>}<section className="panel table"><div className="toolbar"><span>{payments.length} pago(s) registrados</span></div><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Monto</th><th>Método</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Cargando pagos…</td></tr>:payments.length===0?<tr><td colSpan={4}>No hay pagos registrados aún.</td></tr>:payments.map(p=><tr key={p.id}><td>{new Date(`${p.paid_at}T12:00:00`).toLocaleDateString('es-US')}<small className="subtext">{p.reference||'Sin referencia'}</small></td><td>{p.financings?.clients?.full_name}<small className="subtext">{p.financings?.vehicles?`${p.financings.vehicles.make} ${p.financings.vehicles.model}`:'Financiamiento sin vehículo'}</small></td><td>{money.format(p.amount)}</td><td>{p.method}</td></tr>)}</tbody></table></section></>
}
