import { FormEvent, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'

type Vehicle = { id:string; make:string; model:string; year:number|null; vin:string|null; price:number; status:'disponible'|'reservado'|'financiado'|'vendido' }
type VehicleForm = { make:string; model:string; year:string; vin:string; price:string; status:'disponible'|'reservado'|'financiado'|'vendido' }
const empty: VehicleForm = { make:'', model:'', year:'', vin:'', price:'', status:'disponible' }
const money = new Intl.NumberFormat('es-US',{style:'currency',currency:'USD'})

export default function Vehicles() {
  const [vehicles,setVehicles]=useState<Vehicle[]>([]); const [form,setForm]=useState(empty); const [search,setSearch]=useState(''); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Vehicle|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('')
  const load=async()=>{if(!supabase)return;setLoading(true);const {data,error}=await supabase.from('vehicles').select('*').order('created_at',{ascending:false});setLoading(false);if(error)setMessage(`No se pudieron cargar los vehículos: ${error.message}`);else setVehicles(data as Vehicle[])}
  useEffect(()=>{load()},[])
  const close=()=>{setShowForm(false);setEditing(null);setForm(empty)}
  const startEdit=(vehicle:Vehicle)=>{setEditing(vehicle);setForm({make:vehicle.make,model:vehicle.model,year:vehicle.year?String(vehicle.year):'',vin:vehicle.vin??'',price:String(vehicle.price),status:vehicle.status});setShowForm(true)}
  const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const isEditing=Boolean(editing);setSaving(true);setMessage('');const record={...form,year:form.year?Number(form.year):null,price:Number(form.price)};const request=editing?supabase.from('vehicles').update(record).eq('id',editing.id):supabase.from('vehicles').insert(record);const {error}=await request;setSaving(false);if(error){setMessage(`No se pudo guardar: ${error.message}`);return}close();setMessage(isEditing?'Vehículo actualizado correctamente.':'Vehículo registrado correctamente.');load()}
  const remove=async(vehicle:Vehicle)=>{if(!supabase||!confirm(`¿Eliminar ${vehicle.make} ${vehicle.model}?`))return;const {error}=await supabase.from('vehicles').delete().eq('id',vehicle.id);if(error)setMessage(`No se pudo eliminar: ${error.message}`);else{setMessage('Vehículo eliminado.');load()}}
  const shown=vehicles.filter(v=>`${v.make} ${v.model} ${v.vin??''}`.toLowerCase().includes(search.toLowerCase()))
  return <><header><div><span className="eyebrow">GESTIÓN</span><h1>Vehículos</h1><p>Inventario y unidades asignadas a financiamientos.</p></div><button onClick={()=>{setEditing(null);setForm(empty);setShowForm(true)}}>+ Nuevo vehículo</button></header>{message&&<p className="message">{message}</p>}{showForm&&<section className="panel form-panel"><div className="form-title"><h2>{editing?'Editar vehículo':'Registrar vehículo'}</h2><button className="secondary" onClick={close}>Cancelar</button></div><form className="client-form" onSubmit={save}><label>Marca*<input value={form.make} onChange={e=>setForm({...form,make:e.target.value})} required /></label><label>Modelo*<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})} required /></label><label>Año<input type="number" min="1900" max="2100" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></label><label>VIN<input value={form.vin} onChange={e=>setForm({...form,vin:e.target.value})}/></label><label>Precio*<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required /></label><label>Disponibilidad<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as VehicleForm['status']})}><option value="disponible">Disponible</option><option value="reservado">Reservado</option><option value="financiado">Financiado</option><option value="vendido">Vendido</option></select></label><div className="wide"><button disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Guardar vehículo'}</button></div></form></section>}<section className="panel table"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar vehículos…"/><span>{shown.length} vehículo(s)</span></div><table><thead><tr><th>Vehículo</th><th>VIN</th><th>Precio</th><th>Disponibilidad</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Cargando vehículos…</td></tr>:shown.length===0?<tr><td colSpan={5}>No hay vehículos registrados aún.</td></tr>:shown.map(v=><tr key={v.id}><td>{v.make} {v.model}<small className="subtext">{v.year||'Año no indicado'}</small></td><td>{v.vin||'—'}</td><td>{money.format(v.price)}</td><td><span className={`badge ${v.status}`}>{v.status}</span></td><td><button className="secondary" onClick={()=>startEdit(v)}>Editar</button> <button onClick={()=>remove(v)}>Eliminar</button></td></tr>)}</tbody></table></section></>
}
