import { FormEvent, useEffect, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import type { User } from '@supabase/supabase-js'
import { configured, supabase } from './lib/supabase'
import Clients from './pages/Clients'
import Vehicles from './pages/Vehicles'
import Financings from './pages/Financings'
import Payments from './pages/Payments'

const modules = [
  ['/', 'Resumen'], ['/clientes', 'Clientes'], ['/vehiculos', 'Vehículos'], ['/financiamientos', 'Financiamientos'], ['/pagos', 'Pagos']
]
const details: Record<string, {title:string; description:string; columns:string[]}> = {
  clientes: { title:'Clientes', description:'Directorio de solicitantes y clientes activos.', columns:['Nombre', 'Teléfono', 'Documento', 'Estado'] },
  vehiculos: { title:'Vehículos', description:'Inventario y unidades asignadas a financiamientos.', columns:['Vehículo', 'VIN', 'Precio', 'Disponibilidad'] },
  financiamientos: { title:'Financiamientos', description:'Contratos, plazos, tasas y saldos.', columns:['Cliente', 'Vehículo', 'Saldo', 'Estado'] },
  pagos: { title:'Pagos', description:'Cobranza, pagos aplicados y vencimientos.', columns:['Fecha', 'Cliente', 'Monto', 'Método'] }
}

function Login({onLogin}:{onLogin:(u:User)=>void}) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const submit=async(e:FormEvent)=>{e.preventDefault(); if(!supabase)return; setLoading(true); setError(''); const {data,error}=await supabase.auth.signInWithPassword({email,password}); setLoading(false); if(error)setError(error.message); else if(data.user)onLogin(data.user)}
  return <main className="login"><section><span className="eyebrow">TONY FINANCIAL</span><h1>Administración financiera, en un solo lugar.</h1><p>Gestiona clientes, vehículos, contratos y pagos.</p></section><form onSubmit={submit}><h2>Iniciar sesión</h2>{!configured&&<p className="notice">Configura el archivo <code>.env</code> para conectar Supabase.</p>}<label>Correo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<p className="error">{error}</p>}<button disabled={!configured||loading}>{loading?'Ingresando…':'Ingresar'}</button></form></main>
}
function Shell({user}:{user:User}) { const navigate=useNavigate(); const logout=async()=>{await supabase?.auth.signOut();navigate('/login')}; return <div className="shell"><aside><div className="brand">TONY <b>FINANCIAL</b></div><nav>{modules.map(([to,label])=><NavLink key={to} to={to} end={to==='/' }>{label}</NavLink>)}</nav><div className="profile"><small>{user.email}</small><button className="link" onClick={logout}>Cerrar sesión</button></div></aside><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/clientes" element={<Clients/>}/><Route path="/vehiculos" element={<Vehicles/>}/><Route path="/financiamientos" element={<Financings/>}/><Route path="/pagos" element={<Payments/>}/><Route path="/:module" element={<Module/>}/></Routes></main></div> }
function Dashboard(){const [metrics,setMetrics]=useState({portfolio:0,payments:0,clients:0,vehicles:0});const [loading,setLoading]=useState(true);useEffect(()=>{const load=async()=>{if(!supabase)return;const month=new Date().toISOString().slice(0,7);const [f,p,c,v]=await Promise.all([supabase.from('financings').select('principal').eq('status','activo'),supabase.from('payments').select('amount').gte('paid_at',`${month}-01`),supabase.from('clients').select('id',{count:'exact',head:true}).eq('status','activo'),supabase.from('vehicles').select('id',{count:'exact',head:true}).eq('status','disponible')]);const principal=(f.data??[]).reduce((sum,x)=>sum+Number(x.principal),0);const paid=(p.data??[]).reduce((sum,x)=>sum+Number(x.amount),0);setMetrics({portfolio:Math.max(0,principal-paid),payments:paid,clients:c.count??0,vehicles:v.count??0});setLoading(false)};load()},[]);const money=new Intl.NumberFormat('es-US',{style:'currency',currency:'USD'});return <><header><div><span className="eyebrow">PANEL ADMINISTRATIVO</span><h1>Buenos días</h1><p>Vista general de la operación.</p></div></header><div className="stats"><Card label="Cartera activa" value={loading?'…':money.format(metrics.portfolio)}/><Card label="Pagos del mes" value={loading?'…':money.format(metrics.payments)}/><Card label="Clientes activos" value={loading?'…':String(metrics.clients)}/><Card label="Unidades disponibles" value={loading?'…':String(metrics.vehicles)}/></div><section className="panel"><h2>Panel conectado</h2><p>Las métricas se actualizan con la información guardada en Clientes, Vehículos, Financiamientos y Pagos.</p></section></>}
function Card({label,value}:{label:string;value:string}){return <article className="card"><span>{label}</span><strong>{value}</strong></article>}
function Module(){const key=location.pathname.slice(1);const data=details[key];if(!data)return <Navigate to="/" replace/>;return <><header><div><span className="eyebrow">GESTIÓN</span><h1>{data.title}</h1><p>{data.description}</p></div><button>+ Nuevo</button></header><section className="panel table"><div className="toolbar"><input placeholder={`Buscar ${data.title.toLowerCase()}…`}/><button className="secondary">Filtros</button></div><table><thead><tr>{data.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr><td colSpan={data.columns.length}>Sin registros aún. El siguiente paso es conectar este módulo a las tablas de Supabase.</td></tr></tbody></table></section></>}
export default function App(){const [user,setUser]=useState<User|null>(null);const [ready,setReady]=useState(!configured);useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>{setUser(data.user);setReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.unsubscribe()},[]);if(!ready)return null;return <Routes><Route path="/login" element={user?<Navigate to="/"/>:<Login onLogin={setUser}/>}/><Route path="/*" element={user?<Shell user={user}/>:<Navigate to="/login"/>}/></Routes>}
